#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-0 --primary --mode 1920x1080 --rotate normal -r 74.97 --output DVI-D-0 --mode 1680x1050 --rotate normal -r 59.95 --right-of HDMI-0

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DVI-D-0 -d VI VII VIII IX X

sxhkd &
$HOME/.config/polybar/launch.sh

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Thunderbird state=floating
bspc rule -a Yad state=floating
bspc rule -a Firefox desktop='^2'
